site_name: Odoo Documentation
theme:
  name: material
  logo: troc.gif
  palette:
    primary: '#512DA8'  
    accent: '#673AB7'  
    background: '#303030'  
    text: '#FFFFFF'
  extra:
    favicon: odoo.ico  
  features:
    - content.code.copy
    - navigation.sections
    - navigation.tabs
markdown_extensions:
  - admonition:
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true


#plugins:
 # - search
  #- pdf-export


nav:
  - General:
    - Home: index.md
    - Odoo Inventario:  Bussines Process/00_a_Odoo_Inventario_en.md
    - Business Process:
        - Inventory Workflow: Bussines Process/00_flujo_en.md
        - Inventory Process : Bussines Process/01_process.md
        - Create Sales Order: Bussines Process/02_crear_orden_venta.md
        - Automatic Order Delivery: Bussines Process/03_automatic_orden_entrega.md
        - Whop Confirmation: Bussines Process/04_confirmacion_whop.md
        - Process Completion:  Bussines Process/05-_finalizacion_process.md

    - Warehouse team administrative Tasks:

        - Create a contact (FT): Warehouse team administrative Tasks/01-contac_en.md
        - Create a product: Warehouse team administrative Tasks/02-create_product_en.md
        - stock manual adjustment: Warehouse team administrative Tasks/03-ajuste_manual_en.md
        - check stock: Warehouse team administrative Tasks/04-stock_basico _en.md
        - check forecasting: Warehouse team administrative Tasks/05-pronostico_en.md

    - ERP common Tools:
        - Views:
            - Form: ERP common Tools/vista/form_en.md
            - List: ERP common Tools/vista/list.md
            - Graphs: ERP common Tools/vista/graficos_en.md
        - Filter and Search and Group: ERP common Tools/filter_search_en.md
        - Export: ERP common Tools/export_en.md
        - Chatter: ERP common Tools/chatter_en.md
        - Actions: ERP common Tools/accions_en.md
        - Scheduler: ERP common Tools/scheduler_en.md
        - Activities: ERP common Tools/actividades_en.md
      
