name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Se ejecuta en envíos dirigidos a la rama predeterminada
  push:
    branches: ["main"]

  # Permite ejecutar este flujo de trabajo manualmente desde la pestaña Actions
  workflow_dispatch:

jobs:
  # Trabajo de construcción
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x' # Ajusta la versión de Ruby según sea necesario
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Build site
        run: bundle exec jekyll build

  # Trabajo de despliegue
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
